repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 22.3.0
    hooks:
      - id: black-conda
        args:
          - --safe
          - --target-version=py36

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.1.0]
        args:
          - --target-version=py36

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        verbose: true

  - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
    rev: "0.971"
    hooks:
    - id: mypy-conda
      verbose: true
      files: plateau
      additional_dependencies: [types-setuptools, types-decorator, types-simplejson]
